### ISSUE TITLE
GET /api/stable/health

### ISSUE THREAD

**Issue by keskad** [riotkit-org/backup-repository#184]
I suggest to add a healh check endpoint that would check:
- storage connectivity
- database connectivity
- cluster connectivity

**Comment by blackandred** [comment]
Sure I see a value in this. Actually I don't know why this was not added to the v4.0, as we probably would not be able to deploy on Kubernetes with a working health endpoint.

**Comment by blackandred** [comment]
Adding to milestone, would you like to implement or should I assign self?

**Comment by keskad** [comment]
Yes, sure.

**Comment by blackandred** [comment]
I implemented a similar feature already - you can follow the same convention: https://github.com/riotkit-org/backup-repository/issues/183

**Comment by keskad** [comment]
Created a PR: https://github.com/riotkit-org/backup-repository/pull/187
